version: "3.9"
services:
  preview:
    build:
      context: .
      dockerfile: Dockerfile
      target: preview
    platform: linux/amd64
    image: preview-environment
    container_name: preview-container
    ports:
      - "3000:3000"
    volumes:
      - ./docker/nginx-preview.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/htpasswd-preview:/etc/nginx/.htpasswd:ro
      - ./public:/usr/share/nginx/html:ro
    environment:
      - ENV=staging
    networks:
      - app-network
    depends_on:
      - express-app
    restart: unless-stopped

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: express-app
    platform: linux/amd64
    image: express-app-environment
    container_name: express-app-container
    ports:
      - "3001:3001"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
