services:
  preview:
    build:
      context: .
      dockerfile: Dockerfile
      target: preview
    platform: linux/amd64
    image: preview-environment
    container_name: preview-container
    ports:
      - '3000:3000'
    volumes:
      - ./docker/nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/htpasswd-preview:/etc/nginx/.htpasswd:ro
      - ./public:/usr/share/nginx/html:ro
    environment:
      - ENV=staging
    networks:
      - app-network
    depends_on:
      - preview-express-app
    restart: unless-stopped

  preview-express-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: preview-express-app
    environment:
      - ENV=staging
      - BRANCH=preview
    platform: linux/amd64
    image: preview-express-app-environment
    container_name: preview-express-app-container
    ports:
      - '3001:3001'
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
